// try delete comment
DELETE  http://localhost:8000/api/comments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhcmFoIiwiZW1haWwiOiJzYXJhaEBtYWlsLmNvbSIsInVzZXJJZCI6MiwiaXNBZG1pbiI6ZmFsc2UsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjUxMDA0NzgxLjE3LCJleHAiOjQ4MDY2OTczNDF9.WiKxrYueHpmnBfMTdD5fYrGhpyZ9G4jUkeq6R02oj7c

###
DELETE  http://localhost:8000/api/comments/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhcmFoIiwiZW1haWwiOiJzYXJhaEBtYWlsLmNvbSIsInVzZXJJZCI6MiwiaXNBZG1pbiI6ZmFsc2UsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjUxMDA0NzgxLjE3LCJleHAiOjQ4MDY2OTczNDF9.WiKxrYueHpmnBfMTdD5fYrGhpyZ9G4jUkeq6R02oj7c

###
// try delete comment
DELETE  http://localhost:8000/api/comments/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhcmFoIiwiZW1haWwiOiJzYXJhaEBtYWlsLmNvbSIsInVzZXJJZCI6MiwiaXNBZG1pbiI6ZmFsc2UsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjUxMDA0NzgxLjE3LCJleHAiOjQ4MDY2OTczNDF9.WiKxrYueHpmnBfMTdD5fYrGhpyZ9G4jUkeq6R02oj7c

###
// try delete comment by wrong ID
DELETE  http://localhost:8000/api/comments/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhcmFoIiwiZW1haWwiOiJzYXJhaEBtYWlsLmNvbSIsInVzZXJJZCI6MiwiaXNBZG1pbiI6ZmFsc2UsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjUxMDA0NzgxLjE3LCJleHAiOjQ4MDY2OTczNDF9.WiKxrYueHpmnBfMTdD5fYrGhpyZ9G4jUkeq6R02oj7c

###
// try delete comment by filter post
DELETE  http://localhost:8000/api/comments/?filter=post&id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhcmFoIiwiZW1haWwiOiJzYXJhaEBtYWlsLmNvbSIsInVzZXJJZCI6MiwiaXNBZG1pbiI6ZmFsc2UsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjUxMDA0NzgxLjE3LCJleHAiOjQ4MDY2OTczNDF9.WiKxrYueHpmnBfMTdD5fYrGhpyZ9G4jUkeq6R02oj7c

###
// try delete comment when user is not owner nor admin, expected error: Forbidden access
DELETE http://localhost:8000/api/comments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhcmFoIiwiZW1haWwiOiJzYXJhaEBtYWlsLmNvbSIsInVzZXJJZCI6MiwiaXNBZG1pbiI6ZmFsc2UsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjUxMDA0NzgxLjE3LCJleHAiOjQ4MDY2OTczNDF9.WiKxrYueHpmnBfMTdD5fYrGhpyZ9G4jUkeq6R02oj7c

###
// try delete comment with invalid token, expected error: Unauthorized
DELETE http://localhost:8000/api/comments/1
Authorization: Bearer eyJ1c2VybmFtZSI6IlNhcmFoIiwiZW1haWwiOiJzYXJhaEBtYWlsLmNvbSIsInVzZXJJZCI6MiwiaXNBZG1pbiI6ZmFsc2UsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjUxMDA0NzgxLjE3LCJleHAiOjQ4MDY2OTczNDF9.WiKxrYueHpmnBfMTdD5fYrGhpyZ9G4jUkeq6R02oj7c
