// test - login token response - admin
POST http://localhost:8000/api/login
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=app&username=admin@localhost.com&password=123456

###

// test - login token response - not admin
POST http://localhost:8000/api/login
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=app&username=sarah@mail.com&password=password

###

// test - login token error for wrong username
POST http://localhost:8000/api/login
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=app&username=andrei@mail.com&password=password

###

// test - login token error for wrong password
POST http://localhost:8000/api/login
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=app&username=sarah@mail.com&password=passwo

###

// test - login token error for inactive user
POST http://localhost:8000/api/login
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=app&username=cutu@mail.com&password=123456