@hostname = http://localhost:8000

### add new user Sarah

post {{hostname}}/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBsb2NhbGhvc3QuY29tIiwidXNlcklkIjoxLCJpc0FkbWluIjp0cnVlLCJhY3RpdmUiOnRydWUsImlhdCI6MTY1MDk5NTk5OC4yMDcsImV4cCI6NjE2NTA5OTU5Mzh9.lJO9Mtn-xKgcGYqqaZmJLAToFKbCSDc_driFqZqIkpU
Content-Type: application/json

{
    "name": "Sarah",
    "email": "sarah@mail.com",
    "password": "password"
}

### error expected: Unauthorized

post {{hostname}}/api/users
Content-Type: application/json

{
    "name": "Jhon",
    "email": "jhon@mail.com",
    "password": "password"
}

### error expected: name is required

post {{hostname}}/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBsb2NhbGhvc3QuY29tIiwidXNlcklkIjoxLCJpc0FkbWluIjp0cnVlLCJhY3RpdmUiOnRydWUsImlhdCI6MTY1MDk5NTk5OC4yMDcsImV4cCI6NjE2NTA5OTU5Mzh9.lJO9Mtn-xKgcGYqqaZmJLAToFKbCSDc_driFqZqIkpU
Content-Type: application/json

{
    "email": "jhon@mail.com",
    "password": "password"
}

### error expected: email is required

post {{hostname}}/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBsb2NhbGhvc3QuY29tIiwidXNlcklkIjoxLCJpc0FkbWluIjp0cnVlLCJhY3RpdmUiOnRydWUsImlhdCI6MTY1MDk5NTk5OC4yMDcsImV4cCI6NjE2NTA5OTU5Mzh9.lJO9Mtn-xKgcGYqqaZmJLAToFKbCSDc_driFqZqIkpU
Content-Type: application/json

{
    "name": "Jhon",
    "password": "password"
}

### error expected: password is required

post {{hostname}}/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBsb2NhbGhvc3QuY29tIiwidXNlcklkIjoxLCJpc0FkbWluIjp0cnVlLCJhY3RpdmUiOnRydWUsImlhdCI6MTY1MDk5NTk5OC4yMDcsImV4cCI6NjE2NTA5OTU5Mzh9.lJO9Mtn-xKgcGYqqaZmJLAToFKbCSDc_driFqZqIkpU
Content-Type: application/json

{
    "name": "Jhon",
    "email": "jhon@mail.com"
}

### add new user Vlad

post {{hostname}}/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBsb2NhbGhvc3QuY29tIiwidXNlcklkIjoxLCJpc0FkbWluIjp0cnVlLCJhY3RpdmUiOnRydWUsImlhdCI6MTY1MDk5NTk5OC4yMDcsImV4cCI6NjE2NTA5OTU5Mzh9.lJO9Mtn-xKgcGYqqaZmJLAToFKbCSDc_driFqZqIkpU
Content-Type: application/json

{
    "name": "Vlad",
    "email": "vlad@mail.com",
    "password": "password"
}